/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    CustomDatePicker: typeof import('./src/components/CustomDatePicker.vue')['default']
    CustomEventMenu: typeof import('./src/components/CustomEventMenu.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    Grid: typeof import('./src/components/Grid.vue')['default']
    GridActions: typeof import('./src/components/GridActions.vue')['default']
    GridHeader: typeof import('./src/components/GridHeader.vue')['default']
    IconMap: typeof import('./src/components/IconMap.vue')['default']
    Louvor: typeof import('./src/components/Louvor.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    Notifications: typeof import('./src/@core/components/Notifications.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
  }
}
